name: safe-return-backend

services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - db
            - go-backend
        
    db:
        image: postgres:alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d

    go-backend:
        build: ./go-backend
        ports:
            - "8080:8080"
        depends_on:
            - db
        environment:
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_PORT=${DB_PORT}
            - DB_HOST=db

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
volumes:
    db-data:
