basePath: /
definitions:
  endpoints.EmailVerifyRequest:
    properties:
      email:
        type: string
    type: object
  endpoints.EmailVerifyResponse:
    properties:
      response:
        type: string
    type: object
  endpoints.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  endpoints.SignUpRequest:
    properties:
      email:
        type: string
      emailCode:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    type: object
  endpoints.SignUpResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
info:
  contact: {}
  description: APIs for every action to do with Safe Return.
  title: Safe Return Backend
  version: "1.0"
paths:
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Creates a new user account using name, email, password, and a one-time
        email code.
      parameters:
      - description: SignUp request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/endpoints.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Signup successful, returns access and refresh tokens
          schema:
            $ref: '#/definitions/endpoints.SignUpResponse'
        "400":
          description: Incorrect one-time code or bad request
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
        "401":
          description: Missing required fields
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
        "403":
          description: Email not verified / OTP expired
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
        "409":
          description: Email already in use
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
      summary: Sign up a new user
      tags:
      - Auth
  /auth/verify-email:
    post:
      consumes:
      - application/json
      description: Checks if an email is valid and not already in use. Responds with
        plain text.
      parameters:
      - description: Email in JSON
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/endpoints.EmailVerifyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email valid
          schema:
            $ref: '#/definitions/endpoints.EmailVerifyResponse'
        "400":
          description: Invalid email
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
        "401":
          description: Missing required fields
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
        "409":
          description: Email already in use
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
      summary: Verify email for signup
      tags:
      - Auth
swagger: "2.0"
