basePath: /
definitions:
  authendpoints.AccountDeletionRequest:
    properties:
      password:
        type: string
    type: object
  authendpoints.AccountDeletionResponse:
    properties:
      message:
        type: string
    type: object
  authendpoints.emailVerifyRequest:
    properties:
      email:
        type: string
    type: object
  authendpoints.emailVerifyResponse:
    properties:
      response:
        type: string
    type: object
  authendpoints.signUpRequest:
    properties:
      email:
        type: string
      emailCode:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    type: object
  authendpoints.signUpResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  httputils.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  userstatusendpoints.locationRequest:
    properties:
      accuracy:
        type: string
      latitude:
        type: string
      longitude:
        type: string
      speed:
        type: string
      time:
        type: string
    type: object
  userstatusendpoints.locationResponse:
    properties:
      response:
        type: string
    type: object
  userstatusendpoints.setTimeRequest:
    properties:
      time:
        type: string
    type: object
  userstatusendpoints.setTimeResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: APIs for every action to do with Safe Return.
  title: Safe Return Backend
  version: "1.0"
paths:
  /auth/delete-account:
    post:
      consumes:
      - application/json
      description: Use the Password to delete an account from the database
      parameters:
      - description: Deletion request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/authendpoints.AccountDeletionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Deletion successful
          schema:
            $ref: '#/definitions/authendpoints.AccountDeletionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete an account
      tags:
      - Auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Creates a new user account using name, email, password, and a one-time
        email code.
      parameters:
      - description: SignUp request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/authendpoints.signUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Signup successful, returns access and refresh tokens
          schema:
            $ref: '#/definitions/authendpoints.signUpResponse'
        "400":
          description: Incorrect one-time code or bad request
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "401":
          description: Missing required fields
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "403":
          description: Email not verified / OTP expired
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "409":
          description: Email already in use
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
      summary: Sign up a new user
      tags:
      - Auth
  /auth/verify-email:
    post:
      consumes:
      - application/json
      description: Checks if an email is valid and not already in use.
      parameters:
      - description: Email in JSON
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/authendpoints.emailVerifyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email valid
          schema:
            $ref: '#/definitions/authendpoints.emailVerifyResponse'
        "400":
          description: Invalid email
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "401":
          description: Missing required fields
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "409":
          description: Email already in use
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
      summary: Verify email for signup
      tags:
      - Auth
  /user-status/set-time:
    post:
      consumes:
      - application/json
      description: Schedules a function to check on the user to see if they are ok
      parameters:
      - description: Time encoded in json
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/userstatusendpoints.setTimeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userstatusendpoints.setTimeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "401":
          description: Unauthorized - see error message for more detail
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Start a user's trip
      tags:
      - user-status
  /user-status/update-location:
    post:
      consumes:
      - application/json
      description: Inserts a locationRequest into the db describing location, accuracy,
        speed, and time
      parameters:
      - description: Location updater request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/userstatusendpoints.locationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Location updated successfully
          schema:
            $ref: '#/definitions/userstatusendpoints.locationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "401":
          description: Unauthorized - see error message for more detail
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
        "405":
          description: Method not allowed
          schema:
            $ref: '#/definitions/httputils.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Updates the last known location of a user
      tags:
      - user-status
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
